### ISSUE TITLE
Main API server is down

### ISSUE THREAD

**Issue by dragonfirefox** [udit2303/discord-chatbot#2]
I used this API for my chatbot, not the package. Somehow for some days I've noticed the API server is down, `https://api.udit.gq/api/chatbot`. Please review it asap.

**Comment by udit2303** [comment]
Releasing it in sometime, website subscription expired

**Comment by udit2303** [comment]
Fixed, new API server is `https://api/udit.tk`.

**Comment by dragonfirefox** [comment]
Thx
